blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/XplorerHQ/xplorer-community/discussions/new?category=q-a
    about: Ask questions and get help from the community
  - name: Ideas & Suggestions
    url: https://github.com/XplorerHQ/xplorer-community/discussions/new?category=ideas
    about: Share ideas for new features or improvements
